# Site Settings
title: CVWS.NET
tagLine: A Computer Vision Wordsearch Solver written in C#

# Github
githubUser: JoshKeegan
githubRepo: CVWS.NET

# Analytics
gtmKey: G-G7NN4570XR

# Jekyll Settings
markdown: redcarpet
highlighter: pygments