# Site Settings
title: CVWS.NET
tagLine: A Computer Vision Wordsearch Solver written in C#

# Github
githubUser: JoshKeegan
githubRepo: CVWS.NET

# Analytics
analyticsKey: UA-53659461-2

# Jekyll Settings
markdown: redcarpet
highlighter: pygments